name: cat_facts
description: Project about cat facts.


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Widgets
  auto_size_text: ^3.0.0

  # Helpers
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.1.1
  logging: ^1.1.0

  # Architecture
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  auto_route: ^4.2.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.3.1
  retrofit_generator: 4.0.3+1
  build_runner: ^2.2.0
  auto_route_generator: ^4.2.1
  freezed: ^2.1.0+1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/cat_paw.png


  # To add fonts to your application, add an assets section, like this:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
